name: CI Pipeline

# Trigger the workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  run-hello:
    runs-on: ubuntu-latest  # Use latest Ubuntu runner

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use latest Python 3

      # Step 3: Install dependencies (if needed)
      # - name: Install dependencies
      #   run: pip install -r requirements.txt

      # Step 4: Run hello.py
      - name: Run hello.py
        run: python hello.py